# Group Members:
#  Suresh Ande  (G01381683)
#  Chandrashakar Gudipally (G01410349)
#  Abhishek Darana ( G01408181) 
#  Anjan kumar sripati panditaradhyula (G01407403)
#  Shruti Selvaraj Achary (G01447238)
# swe645as3


FROM openjdk:17
COPY SWE645AS3-0.0.1-SNAPSHOT.jar swe645as3.jar
ENTRYPOINT ["java", "-jar", "/swe645as3.jar"]
EXPOSE 8080
