pipeline {
    agent any

    environment {
        DOCKERHUB_CRED_ID = 'dockerhubcred'
        IMAGE_NAME = 'swe645as3'
        IMAGE_TAG = "${new Date().format('yyyyMMddHHmmss')}"
        DOCKER_REGISTRY = 'suresh999'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR with Maven') {
            steps {
                // Assuming pom.xml is also inside SWE645AS3/SWE645AS3
                dir('SWE645AS3/SWE645AS3') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CRED_ID, passwordVariable: 'DOCKERHUB_PASS', usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin"
                        // Building the Docker image from the SWE645AS3 directory
                        // Assuming the Dockerfile is located in SWE645AS3/SWE645AS3
                        sh "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -f SWE645AS3/SWE645AS3/Dockerfile ."
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CRED_ID, passwordVariable: 'DOCKERHUB_PASS', usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage("Deploying to Rancher as single pod") {
            steps {
                sh "kubectl set image deployment/studentsurvey-pipeline container-0=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -n default"
            }
        }

        stage("Deploying to Rancher with load balancer") {
            steps {
                sh "kubectl set image deployment/studentsurvey-lb container-0=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -n default"
            }
        }
    }

    post {
        always {
            sh "docker logout"
        }
    }
}
