// Group Members:
// Suresh Ande (G01381683)
// Chandrashakar Gudipally (G01410349)
// Abhishek Darana (G01408181)
// Anjan kumar sripati panditaradhyula (G01407403)

// Demo

pipeline {
    agent any

    environment {
        // Set the Docker Hub credentials ID
        DOCKERHUB_CRED_ID = 'dockerhubcred'
        // Define the image name and tag
        IMAGE_NAME = 'swe645as3'
        IMAGE_TAG = "${new Date().format('yyyyMMddHHmmss')}"
        // Define the Docker registry
        DOCKER_REGISTRY = 'suresh999'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR with Maven') {
            steps {
                dir('SWE645AS3') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CRED_ID, passwordVariable: 'DOCKERHUB_PASS', usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin"
                        // Point to the Dockerfile inside the SWE645AS3 directory
                        sh "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -f SWE645AS3/Dockerfile SWE645AS3"
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CRED_ID, passwordVariable: 'DOCKERHUB_PASS', usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Update the Kubernetes deployment with the new image
                    // Ensure that kubectl is configured to communicate with your Kubernetes cluster
                    sh "kubectl set image deployment/my-deployment my-container=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --record"
                    // Replace "my-deployment" and "my-container" with your actual deployment and container names
                }
            }
        }
    }

    post {
        always {
            // Logout from Docker after the build process
            sh "docker logout"
        }
    }
}
