// Group Members:
//  Suresh Ande  (G01381683)
//  Chandrashakar Gudipally (G01410349)
//  Abhishek Darana ( G01408181) 
//  Anjan kumar sripati panditaradhyula (G01407403)
//  Shruti Selvaraj Achary (G01447238)
// swe645as3




pipeline {
    environment {
        registryCredential = 'dockerhubcred'
        dateTag = new Date().format("yyyyMMdd-HHmmss")
    }
    agent any
    tools {
        maven 'Maven 3.8.6'
    }
    stages {
        stage('Maven clean & Install') {
            steps {
                script {
                    dir('SWE645AS3') {
                        sh 'mvn clean install'
                    }
                }
            }
        }
        stage('Build Docker Image and Push') {
            steps {
                script {
                    // Ensure you're in the correct directory and specify the path to the Dockerfile
                    dir('SWE645AS3') { // Change to the directory containing the Dockerfile
                        docker.withRegistry('', registryCredential) {
                            def app = docker.build("suresh999/swe645as3:${dateTag}", '-f Dockerfile --no-cache .')
                            app.push()
                        }
                    }
                }
            }
        }
        stage('Deploying to single node in Rancher') {
            steps {
                script {
                    sh "kubectl set image deployment/studentsurvey-pipeline container-0=suresh999/swe645as3:${dateTag}"
                    sh "kubectl set image deployment/studentsurvey-lb container-0=suresh999/swe645as3:${dateTag}"
                }
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }    
}
